### ISSUE TITLE
Example plain text variants aren't recognized

### ISSUE THREAD

**Issue by rmzelle** [evocellnet/mutfunc-webserver#2]
When I copy and paste any of the plain text variant examples at http://mutfunc.com/help (which seem to be all for S. cerevisiae, although this isn't indicated), I get the following error:

> Error validating variants
> No mutations found. Please ensure you have entered or uploaded mutations and try again.

**Comment by rmzelle** [comment]
Never mind. I tried two different browsers, but both had Privacy Badger (https://www.eff.org/privacybadger) installed. Disabling this fixed the issue.

It would be a good thing if the instructions clearly indicated that the example variants are for S. cerevisiae, though.

**Comment by mgalardini** [comment]
Hi, thanks for reporting this; although it is not stated clearly, the organism dropdown switches to "S. cerevisiae" when the "load sample" link is selected. We'll evaluate whether this should be reported to the users more clearly.

**Comment by rmzelle** [comment]
> although it is not stated clearly, the organism dropdown switches to "S. cerevisiae" when the "load sample" link is selected. We'll evaluate whether this should be reported to the users more clearly.

Ah, right. But in my case, I read http://mutfunc.com/help, which just says "Here are a few valid examples
YDL203C K184A   ACK1 K184A   Q07622 184 K/A  chrI 61165 T/A"

I read this documentation, copied and pasted these examples to the Submit tab, and was then left wondering which organism to select. Same went for the placeholder variants shown at http://mutfunc.com/submit.

**Comment by rmzelle** [comment]
Also, as a very minor niggle, http://mutfunc.com/submit has the species names in the dropdown menu ("S. cerevisiae", "E. coli", and "H. sapiens"), but http://mutfunc.com/help uses "Yeast", "Ecoli" [sic, should be "E. coli"], and "Human". It would be more consistent to use the species names for the latter as well for all three organisms.
