### ISSUE TITLE
Error occurred when trying to run even the sample data

### ISSUE THREAD

**Issue by lecob** [evocellnet/mutfunc-webserver#4]
As written in the title, I have an error even when I try to submit the sample data.
This is the output that I receive:

Oops, an error occurred
This exception has been logged with id 7ce7kn5gl.

**Comment by mgalardini** [comment]
Hi, I just tried to run mutfunc with sample data for all three species and got no error. I assume you might have encountered a glitch in the computational infrastructure used by mutfunc. Closing the issue for now, but do let me know if it persists for you and I can look into it again.
